hcloud_token: ENC[AES256_GCM,data:n71ubbnXZnoKbtf5zD2dPzS/7v58EhZgUlVZHJQCNazHD+IUobA1x7G2yQlD+08snLzX5GeoxDPfjk/zf4WjNw==,iv:MRhHolNC/qLtBqEhNi1X7WCXskp9u//LlE+HMZqZMOU=,tag:xtWxnZLvsZbr/i4J+HEzXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bDNhVE0xalh6eXQ1RTlm
            RmVDWmZLa2ZrSjhzT1I4VjRQRDh0dTUzZEFRCmVKL2VqdE5jWHBGMXpLK25wN24x
            QWlEdjVENTBTVHhUdUlIazN4eUlUMlUKLS0tIEFTRzhmYVJjQlVDM0VxK3V1WFAr
            MWhYWm9DeExsWTVWZVRvY2J6RnVCNE0KTI59rdKWss/cMXqgPy7CjEYW7LR+7+ze
            U/O6h/MpkR0fQ4gQTJNyUHC1frWQKfc8C8S4x+NO6vILpEAqWvWszA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msj34ws4vhrdtdew6tt65f76mvfacegs06dvxr8wfghs3hfh6eqqkax93f
    lastmodified: "2026-06-22T00:16:19Z"
    mac: ENC[AES256_GCM,data:ZYDqbkzJ6RiTIl//A/GHBINif/DqSDG3VnpXBMl86kBni50P9eYUURKdjfif8NhFGza1pPJI6zSo5YGRP2uQkeOdNal7I8Ydy+2VwnUWr3l4Qzw6lQ62X3/BNmKCm1jOcjdyFgphU250QSfNYLW8hx+fuqd45U6PVYVE36Byl5s=,iv:gi2Zd0yrydX7PiGAUx2J8Hg7mb/4F6Y9+vjG4G3GLTA=,tag:LaCYF4a2xXvPSYrXnXCtKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
