hcloud_token: ENC[AES256_GCM,data:GGki2Vofn8Rnp81gJv9Z4GO7GFfDeLxUoAfAVB3a5az7awnL4L1B6L9jgu78aVm9kVrIHbtCQIcIqud4dPbu1Q==,iv:TUBRQv1H5klZwuGpn+4khW6HAHZR+VX7HGVy5KVpLWY=,tag:7C5OJTjtjvZUR275C17vWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6bDNhVE0xalh6eXQ1RTlm
            RmVDWmZLa2ZrSjhzT1I4VjRQRDh0dTUzZEFRCmVKL2VqdE5jWHBGMXpLK25wN24x
            QWlEdjVENTBTVHhUdUlIazN4eUlUMlUKLS0tIEFTRzhmYVJjQlVDM0VxK3V1WFAr
            MWhYWm9DeExsWTVWZVRvY2J6RnVCNE0KTI59rdKWss/cMXqgPy7CjEYW7LR+7+ze
            U/O6h/MpkR0fQ4gQTJNyUHC1frWQKfc8C8S4x+NO6vILpEAqWvWszA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1msj34ws4vhrdtdew6tt65f76mvfacegs06dvxr8wfghs3hfh6eqqkax93f
    lastmodified: "2026-06-10T11:32:25Z"
    mac: ENC[AES256_GCM,data:quDx+4u0EtM1akRV7XkuTfiEaG+dBN88JxB2xRLrgu9aJs3DFJJ1z3/11iskjvQt+hlWZ3wveo304G0T/cLSj+Um5OUTAXYm5dFRqJxlY23Eq/TKaHIkJqCmdTIz8Zxa/nSo/KDMVjZa+Cg6bM5bHFZOVr344/s343TZ8iqBzjI=,iv:bWcsM6RDmCCn5XAhWvi+7k3k4luwpybOyhz5L7/pNI0=,tag:GLiu0bRPJc3RccRXIVaGZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
